server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: mongodb
    static_configs:
    - targets:
        - localhost
      labels:
        job: mongodb
        __path__: /var/log/*.log
